import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets

from sql_main import Ui_MainWindow

sqlite_connection_02 = sqlite3.connect("setting.db")
cursor_02 = sqlite_connection_02.cursor()
sqlite_connection_01 = sqlite3.connect("id.db")
cursor_01 = sqlite_connection_01.cursor()



class Setting(object):
    def setupUi(self, Form):
        username = cursor_01.execute(f"""SELECT login FROM autorization WHERE online='True'""").fetchone()
        value = cursor_02.execute(
            f"""SELECT font,title_font,color_table,color_table_selection,width_loko,width_detal,width_masters,image_size,width_stok FROM setting WHERE user='{username[0]}'""").fetchone()
        Form.setObjectName("Form")
        Form.resize(1160, 657)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("train.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -20, 1381, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("sql_maket/полотно.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 310, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 390, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 470, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(230, 36, 191, 31))
        self.horizontalSlider.setMinimum(8)
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(440, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(310, 340, 241, 31))
        self.horizontalSlider_2.setMinimum(900)
        self.horizontalSlider_2.setMaximum(1325)
        self.horizontalSlider_2.setSingleStep(5)
        self.horizontalSlider_2.setProperty("value", 1320)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(Form)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(360, 417, 231, 31))
        self.horizontalSlider_3.setMinimum(900)
        self.horizontalSlider_3.setMaximum(1315)
        self.horizontalSlider_3.setSingleStep(5)
        self.horizontalSlider_3.setProperty("value", 1310)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(Form)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(370, 496, 221, 31))
        self.horizontalSlider_4.setMinimum(700)
        self.horizontalSlider_4.setMaximum(1035)
        self.horizontalSlider_4.setSingleStep(5)
        self.horizontalSlider_4.setProperty("value", 1030)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(570, 340, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(610, 414, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(610, 494, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(210, 180, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Голубой")
        self.comboBox.addItem("Красный")
        self.comboBox.addItem("Фиолетовый")
        self.comboBox.addItem("Белый")
        self.comboBox.addItem("Зелёный")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 260, 191, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("Голубой")
        self.comboBox_2.addItem("Красный")
        self.comboBox_2.addItem("Фиолетовый")
        self.comboBox_2.addItem("Белый")
        self.comboBox_2.addItem("Зелёный")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 80, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(850, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(1040, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setStyleSheet("color: rgb(189, 255, 200);")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalSlider_5 = QtWidgets.QSlider(Form)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(380, 105, 191, 31))
        self.horizontalSlider_5.setMinimum(10)
        self.horizontalSlider_5.setMaximum(22)
        self.horizontalSlider_5.setSingleStep(5)
        self.horizontalSlider_5.setProperty("value", 10)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(590, 99, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(850, 600, 161, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(229, 229, 229);\n"
"    color:rgb(0, 0, 0)}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 255);}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\User\\PycharmProjects\\SQL_Maket\\../../Desktop/png/tool.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(1020, 600, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(229, 229, 229);\n"
"    color:rgb(0, 0, 0)}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 255);}")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(850, 550, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(229, 229, 229);\n"
                                        "    color:rgb(0, 0, 0)}\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgb(255, 255, 255);}")
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(30, 590, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.horizontalSlider_6 = QtWidgets.QSlider(Form)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(360, 620, 231, 31))
        self.horizontalSlider_6.setMinimum(50)
        self.horizontalSlider_6.setMaximum(100)
        self.horizontalSlider_6.setSingleStep(5)
        self.horizontalSlider_6.setProperty("value", 75)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(30, 530, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.horizontalSlider_7 = QtWidgets.QSlider(Form)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(330, 560, 231, 31))
        self.horizontalSlider_7.setMinimum(700)
        self.horizontalSlider_7.setMaximum(1200)
        self.horizontalSlider_7.setSingleStep(5)
        self.horizontalSlider_7.setProperty("value", 1030)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_6")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(610, 620, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(580, 558, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.number(value[0])  # Вызов number
        self.number1(value[1])
        self.number2(value[4])
        self.number3(value[5])
        self.number4(value[6])
        self.number5(value[7])
        self.number6(value[8])
        self.horizontalSlider.valueChanged.connect(self.number)  # для изменения значения
        self.horizontalSlider_5.valueChanged.connect(self.number1)
        self.horizontalSlider_2.valueChanged.connect(self.number2)
        self.horizontalSlider_3.valueChanged.connect(self.number3)
        self.horizontalSlider_4.valueChanged.connect(self.number4)
        self.horizontalSlider_6.valueChanged.connect(self.number5)
        self.horizontalSlider_7.valueChanged.connect(self.number6)
        self.comboBox.setCurrentText(str(value[2]))
        self.comboBox_2.setCurrentText(str(value[3]))
        def puff():
            colors = {"rgb(170, 255, 255)": "Голубой",
                      "rgb(255, 85, 85)": "Красный",
                      "rgb(198, 140, 255)": "Фиолетовый",
                      "rgb(255, 255, 255)": "Белый",
                      "rgb(92, 255, 116)": "Зелёный"}
            font=int(self.label_8.text())
            title_font=int(self.label_13.text())
            color_table=str(self.comboBox.currentText())
            keys_1 = [key for key in colors if colors[key] == color_table]
            rgb=str(keys_1[0])
            color_table_selection = str(self.comboBox_2.currentText())
            keys_2 = [key for key in colors if colors[key] == color_table_selection]
            rgb_selection=str(keys_2[0])
            width_loko=int(self.label_9.text())
            width_detal=int(self.label_10.text())
            width_masters=int(self.label_11.text())
            image_size=int(self.label_15.text())
            width_stok=int(self.label_19.text())
            cursor_02.execute(
                f"""UPDATE setting SET font='{font}',title_font='{title_font}',color_table='{color_table}',color_table_selection='{color_table_selection}',
                width_loko='{width_loko}',width_detal='{width_detal}',width_masters='{width_masters}',image_size='{image_size}', 
                rgb='{rgb}',rgb_selection='{rgb_selection}',width_stok='{width_stok}' WHERE user='{username[0]}'""")
            sqlite_connection_02.commit()
        def default():
            self.number(11)  # Вызов number
            self.number1(11)
            self.number2(1311)
            self.number3(1321)
            self.number4(1030)
            self.number5(75)
            self.number6(1030)
            self.horizontalSlider.valueChanged.connect(self.number)  # для изменения значения
            self.horizontalSlider_5.valueChanged.connect(self.number1)
            self.horizontalSlider_2.valueChanged.connect(self.number2)
            self.horizontalSlider_3.valueChanged.connect(self.number3)
            self.horizontalSlider_4.valueChanged.connect(self.number4)
            self.horizontalSlider_6.valueChanged.connect(self.number5)
            self.horizontalSlider_7.valueChanged.connect(self.number6)
            self.comboBox.setCurrentText(str("Белый"))
            self.comboBox_2.setCurrentText(str("Голубой"))
            cursor_02.execute(
                f"""UPDATE setting SET font=11,title_font=11,color_table='Белый',color_table_selection='Голубой',
                            width_loko=1311,width_detal=1321,width_masters=1030,image_size=75, 
                            rgb='rgb(255, 255, 255)',rgb_selection='rgb(170, 255, 255)',width_stok=1030 WHERE user='{username[0]}'""")
            sqlite_connection_02.commit()
        self.pushButton_10.clicked.connect(default)
        self.pushButton_8.clicked.connect(puff)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def number(self, value):
        self.label_8.setText(str(value))
        self.horizontalSlider.setValue(value)

    def number1(self, value):
        self.label_13.setText(str(value))
        self.horizontalSlider_5.setValue(value)

    def number2(self, value):
        self.label_9.setText(str(value))
        self.horizontalSlider_2.setValue(value)

    def number3(self, value):
        self.label_10.setText(str(value))
        self.horizontalSlider_3.setValue(value)

    def number4(self, value):
        self.label_11.setText(str(value))
        self.horizontalSlider_4.setValue(value)

    def number5(self, value):
        self.label_15.setText(str(value))
        self.horizontalSlider_6.setValue(value)

    def number6(self, value):
        self.label_19.setText(str(value))
        self.horizontalSlider_7.setValue(value)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.label_2.setText(_translate("Form", "Размер шрифта:"))
        self.label_3.setText(_translate("Form", "Цвет таблицы:"))
        self.label_4.setText(_translate("Form", "Цвет выделения:"))
        self.label_5.setText(_translate("Form", "Ширина таблиц в локо:"))
        self.label_6.setText(_translate("Form", "Ширина таблицы в деталях:"))
        self.label_7.setText(_translate("Form", "Ширина таблицы в мастерах:"))
        self.label_12.setText(_translate("Form", "Размер шрифта в загаловках:"))
        self.label_16.setText(_translate("Form", "Настройки для пользователя:"))
        self.label_18.setText(_translate("Form", "Ширина таблицы в складе:"))
        username = cursor_01.execute(f"""SELECT login FROM autorization WHERE online='True'""").fetchone()
        self.label_17.setText(_translate("Form", f"{username[0]}"))
        self.pushButton_8.setText(_translate("Form", "Применить"))
        self.pushButton_9.setText(_translate("Form", "Отмена"))
        self.pushButton_10.setText(_translate("Form", "По умолчанию"))
        self.label_14.setText(_translate("Form", "Размер картинки в деталях:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Setting()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
